export const SITE_CONFIG = {
  name:        'Muhammad Saifullah',
  shortName:   'Muhammad Saifullah',
  tagline:     'Designing Websites That Build Businesses.',
  subTagline:  'Frontend Web Developer & Web Designer creating modern, responsive, high-performance websites for businesses, schools, startups, and personal brands.',
  location:    'Haripur, KPK, Pakistan',
  email:       'iamsaifi17@gmail.com',
  phone:       '+92-318-5352563',

  social: {
    linkedin:  'https://www.linkedin.com/in/muhammad-saifullah-8a3469416',
    fiverr:    'https://www.fiverr.com/saifii1201',
    facebook:  'https://www.facebook.com/share/1ApyuC5MMY/',
    twitter:   'https://twitter.com/iamsaifi17',
    instagram: 'https://instagram.com/iamsaifi17',
    github:    'https://github.com/iamsaifi17',
  },

  seo: {
    title:       'Muhammad Saifullah | Frontend Web Developer & Web Designer',
    description: 'Professional Frontend Web Developer creating modern, responsive, high-performance websites for businesses, schools, startups, and personal brands. Based in Pakistan.',
    keywords:    'web developer Pakistan, frontend developer Pakistan, web designer Pakistan, Next.js developer, Muhammad Saifullah, website developer Haripur',
    siteUrl:     'https://saifullah-portfolio.vercel.app',
    ogImage:     '/images/og-image.jpg',
    twitterHandle: '@iamsaifi17',
  },

  about: {
    headline: 'Frontend Developer Who Builds Websites That Work For You',
    bio: [
      "I'm Muhammad Saifullah — a Frontend Web Developer and Web Designer from Haripur, KPK, Pakistan. I build modern, responsive, high-performance websites that help businesses grow their online presence and attract more customers.",
      "With a BS English degree and self-taught web development skills, I combine clean code with compelling design to deliver websites that don't just look great — they convert visitors into clients. I specialize in Next.js, React, Tailwind CSS, and modern UI/UX design.",
      "I have built real live websites for businesses, schools, and personal brands — and I bring the same level of care, detail, and professionalism to every project, no matter the size. Based in Pakistan, serving clients worldwide.",
    ],
    mission: "To help businesses, schools, and personal brands grow online through modern, fast, and beautiful websites — built with clean code, delivered on time, and designed to make a lasting impression.",
    stats: [
      { value: '3+',   label: 'Live Websites Built'  },
      { value: 'BS',   label: 'English Graduate'      },
      { value: '48h',  label: 'Fast Turnaround'       },
      { value: '100%', label: 'Client Satisfaction'   },
    ],
  },

  skills: [
    { name: 'HTML5 & CSS3',              level: 92 },
    { name: 'JavaScript',                level: 80 },
    { name: 'React & Next.js',           level: 82 },
    { name: 'Tailwind CSS',              level: 90 },
    { name: 'Responsive Web Design',     level: 93 },
    { name: 'UI/UX Design',              level: 85 },
    { name: 'Git & GitHub',              level: 80 },
    { name: 'SEO & Performance',         level: 83 },
    { name: 'Vercel Deployment',         level: 95 },
    { name: 'AI-Assisted Development',   level: 90 },
  ],

  services: [
    {
      id:          'business-website',
      icon:        '🏢',
      title:       'Business Websites',
      description: 'Professional websites for businesses of all sizes — built to impress customers, generate leads, and grow your brand online.',
      features:    ['Custom Design', 'Mobile Responsive', 'Contact Forms', 'WhatsApp Integration', 'SEO Ready', 'Fast Loading', 'Vercel Deployment'],
      price:       'Starting at $80',
      popular:     true,
    },
    {
      id:          'portfolio-website',
      icon:        '💼',
      title:       'Portfolio Websites',
      description: 'Stunning personal portfolio websites for freelancers, developers, writers, and creatives who want to stand out and attract clients.',
      features:    ['Premium Design', 'Smooth Animations', 'Project Showcase', 'Testimonials Section', 'Contact Form', 'SEO Optimized', 'Mobile First'],
      price:       'Starting at $50',
      popular:     false,
    },
    {
      id:          'school-website',
      icon:        '🏫',
      title:       'School & Education Websites',
      description: 'Clean, professional websites for schools, colleges, and educational institutions — easy to navigate for students, parents, and staff.',
      features:    ['Admissions Page', 'Staff Directory', 'Gallery Section', 'News & Events', 'Mobile Friendly', 'Easy to Update', 'Fast Loading'],
      price:       'Starting at $70',
      popular:     false,
    },
    {
      id:          'landing-page',
      icon:        '🚀',
      title:       'Landing Pages',
      description: 'High-converting landing pages designed to turn visitors into customers — perfect for product launches, campaigns, and promotions.',
      features:    ['Conversion Focused', 'Fast Loading', 'CTA Optimized', 'Mobile First', 'Analytics Ready', 'Custom Design', 'SEO Ready'],
      price:       'Starting at $30',
      popular:     false,
    },
    {
      id:          'ui-design',
      icon:        '🎨',
      title:       'UI/UX Design',
      description: 'Modern interface design that looks beautiful and feels intuitive — creating experiences users love and remember.',
      features:    ['Custom UI Design', 'Modern Aesthetic', 'User Friendly', 'Brand Consistent', 'Responsive Layouts', 'Pixel Perfect', 'Fast Delivery'],
      price:       'Starting at $25',
      popular:     false,
    },
  ],

  portfolio: [
    {
      id:       1,
      title:    'MashAllah Parrot House',
      client:   'Parrot Business — Karachi, Pakistan',
      category: 'Web Development',
      tags:     ['Next.js', 'Business Website', 'WhatsApp Integration'],
      excerpt:  'A modern premium website for a parrot business featuring bird listings, responsive design, WhatsApp integration, and elegant UI. Built with Next.js and Tailwind CSS.',
      metrics:  { Tech: 'Next.js', Type: 'Business', Status: 'Live' },
      image:    '/images/portfolio/portfolio-1.jpg',
      liveUrl:  'https://mashallah-parrot-house-giml.vercel.app/',
    },
    {
      id:       2,
      title:    'Bright School',
      client:   'Educational Institution',
      category: 'Web Development',
      tags:     ['Next.js', 'School Website', 'Responsive'],
      excerpt:  'A clean and responsive educational website designed for a modern school with professional layouts, admissions info, and user-friendly navigation.',
      metrics:  { Tech: 'Next.js', Type: 'Education', Status: 'Live' },
      image:    '/images/portfolio/portfolio-2.jpg',
      liveUrl:  'https://bright-school-ten.vercel.app/',
    },
    {
      id:       3,
      title:    'Joylyn Rosa Portfolio',
      client:   'SEO Content Writer — Philippines',
      category: 'Web Development',
      tags:     ['Next.js', 'Portfolio', 'Animations'],
      excerpt:  'A modern personal portfolio website built for SEO Content Writer Joylyn Rosa — premium design, smooth animations, responsive layout, and professional presentation.',
      metrics:  { Tech: 'Next.js', Type: 'Portfolio', Status: 'Live' },
      image:    '/images/portfolio/portfolio-3.jpg',
      liveUrl:  'https://jolynrosa123-gtnc.vercel.app/',
    },
    {
      id:       4,
      title:    'Muhammad Saifullah Portfolio',
      client:   'Personal Brand',
      category: 'Web Development',
      tags:     ['Next.js', 'Portfolio', 'Tailwind CSS'],
      excerpt:  'This very website — a fully responsive professional portfolio built with Next.js, Tailwind CSS, and Framer Motion. Dark luxury theme with gold accents.',
      metrics:  { Tech: 'Next.js', Type: 'Portfolio', Status: 'Live' },
      image:    '/images/portfolio/portfolio-4.jpg',
      liveUrl:  'https://saifullah-portfolio.vercel.app',
    },
  ],

  testimonials: [
    {
      id:          1,
      name:        'Joylyn Rosa',
      role:        'SEO Content Writer',
      country:     '🇵🇭 Philippines',
      rating:      5,
      text:        "I'm so glad I found Muhammad Saifullah. I needed a portfolio that would help me stand out and attract clients, and he absolutely delivered. The moment I saw the final result, I was honestly so happy — it looked even better than I imagined and gave me so much more confidence in putting myself out there. What I appreciated most was how kind, patient, and easy he was to work with. He really listened to what I wanted, paid attention to the little details, and made sure everything felt right. You can tell he genuinely cares about doing a great job and helping his clients succeed. If you're thinking about working with Muhammad, don't hesitate. I'm incredibly grateful for his work and couldn't be happier with my portfolio. Thank you so much!",
      linkedinUrl: 'https://www.linkedin.com/posts/joylyn-rosa-040143415_joylyn-rosa-seo-content-writer-virtual-activity-7481960809573699584-dM36',
      websiteUrl:  'https://jolynrosa123-gtnc.vercel.app/',
      image:       '/images/testimonials/joylyn-rosa.jpg',
    },
    {
      id:          2,
      name:        'Ahmed Khan',
      role:        'Founder, Vision Digital',
      country:     '🇵🇰 Pakistan',
      rating:      5,
      text:        'Muhammad delivered a modern website that exceeded our expectations. His communication, attention to detail, and commitment to quality made the entire experience smooth and professional. I would highly recommend him to anyone looking for a skilled and reliable web developer.',
      linkedinUrl: null,
      websiteUrl:  null,
      image:       '/images/testimonials/client-2.jpg',
    },
  ],

  resume: {
    downloadUrl: '/resume/Muhammad-Saifullah-CV.pdf',
    summary: 'Creative and driven BS English graduate with a strong foundation in web development, writing, and AI-powered workflows. Experienced in building modern responsive websites using Next.js, React, and Tailwind CSS. Proficient in using AI tools including ChatGPT, Claude, and Gemini to accelerate development. Owns multiple live websites demonstrating real digital presence and technical capability.',
    experience: [
      {
        title:   'Freelance Frontend Web Developer',
        company: 'Self-Employed',
        period:  '2024 – Present',
        points:  [
          'Built and deployed 3+ live websites for real clients using Next.js and Tailwind CSS',
          'Designed responsive mobile-first UI/UX interfaces with modern animations',
          'Integrated WhatsApp, contact forms, booking systems, and admin dashboards',
          'Created social media content for Instagram, Facebook, LinkedIn, and YouTube',
          'Used ChatGPT, Claude, and Gemini to accelerate development and content workflows',
        ],
      },
      {
        title:   'Research Writer & Content Analyst',
        company: 'Academic Research Project',
        period:  'Jan 2026 – Jun 2026',
        points:  [
          'Researched and wrote a complete long-form academic paper on postcolonial literature',
          'Title: Moral Decay and Social Hypocrisy — A Postcolonial Study of Mohsin Hamid\'s Moth Smoke',
          'Converted complex research into compelling, structured narratives',
          'Used AI tools to synthesize research, iterate content, and optimize writing quality',
        ],
      },
    ],
    education: [
      { degree: 'Bachelor of Science in English (BS English)', school: 'Govt. Akhtar Nawaz Khan (Shaheed) Degree College KTS', period: '2022 – 2026' },
      { degree: 'Diploma in Surgical Technician', school: 'FIMS', period: '2020' },
      { degree: 'FSC Premedical', school: 'Govt. PG College Haripur', period: '2020' },
    ],
    techSkills:    ['HTML5', 'CSS3', 'JavaScript', 'React', 'Next.js', 'Tailwind CSS', 'Responsive Design', 'UI/UX Design', 'Git & GitHub', 'SEO Basics', 'Website Optimization', 'Vercel Deployment'],
    contentSkills: ['Social Media Copywriting', 'Blog & Article Writing', 'Brand Storytelling', 'Content Calendar Planning', 'AI-Assisted Content Creation', 'Caption & Script Writing'],
    aiTools:       ['ChatGPT', 'Claude (Anthropic)', 'Gemini'],
    languages:     ['English (Fluent)', 'Urdu (Native)', 'Pashto', 'Hindko', 'Punjabi'],
  },

  blogPosts: [
    {
      slug:     'how-to-build-a-professional-website-2025',
      title:    'How to Build a Professional Website in 2025 — Complete Guide',
      excerpt:  'Everything you need to know to build a fast, modern website from scratch using Next.js and Tailwind CSS. Step by step, no experience needed.',
      category: 'Web Development',
      readTime: '8 min read',
      date:     '2025-06-01',
      image:    '/images/blog/blog-1.jpg',
      featured: true,
    },
    {
      slug:     'why-every-business-needs-a-website',
      title:    'Why Every Small Business in Pakistan Needs a Website in 2025',
      excerpt:  'Still relying only on Facebook and WhatsApp? Here is why a proper website will completely change things for your brand and revenue.',
      category: 'Business',
      readTime: '5 min read',
      date:     '2025-05-15',
      image:    '/images/blog/blog-2.jpg',
      featured: false,
    },
    {
      slug:     'nextjs-vs-wordpress',
      title:    'Next.js vs WordPress — Which is Better for Your Business Website?',
      excerpt:  'Both are popular — but which one should you choose? An honest comparison from a developer who has worked with both platforms.',
      category: 'Web Development',
      readTime: '6 min read',
      date:     '2025-04-20',
      image:    '/images/blog/blog-3.jpg',
      featured: false,
    },
  ],

  faq: [
    {
      q: 'What types of websites do you build?',
      a: 'I build business websites, portfolio websites, school and education websites, landing pages, and modern UI/UX interfaces. All websites are built with Next.js and Tailwind CSS — fully responsive, fast, and SEO-ready.',
    },
    {
      q: 'How long does it take to build a website?',
      a: 'A landing page can be done in 24 to 48 hours. A standard website takes 3 to 7 days. A complex website with custom features may take up to 14 days. I always give a clear timeline upfront.',
    },
    {
      q: 'How much does a website cost?',
      a: 'A landing page starts at $30, a portfolio website starts at $50, a school website starts at $70, and a business website starts at $80. Honest, transparent pricing — no hidden charges.',
    },
    {
      q: 'Will my website work on mobile phones?',
      a: 'Absolutely. Every website I build is fully mobile-responsive and tested on phones, tablets, and desktops.',
    },
    {
      q: 'Do you host the website for free?',
      a: 'Yes! I deploy all websites on Vercel for free. You only need a domain name if you want one — around $10 to $15 per year. Hosting is completely free.',
    },
    {
      q: 'Can I update the website myself after it is built?',
      a: 'Yes — I build websites so that content is easy to edit. I also provide a simple guide explaining how to make changes yourself without coding knowledge.',
    },
    {
      q: 'Do you offer revisions?',
      a: 'Yes — every project includes 2 rounds of free revisions. I want you to be 100% happy. We keep working until everything is exactly right.',
    },
    {
      q: 'How do I get started?',
      a: 'Click the Hire Me button or send me a message through the contact form. Tell me about your project and I will reply within 24 hours with a proposal, timeline, and price.',
    },
  ],
};
