// lib/config.js — Edit ALL your personal info here

export const SITE_CONFIG = {
  name:        'Muhammad Saifullah',
  shortName:   'Muhammad Saifullah',
  tagline:     'Designing Websites That Grow Businesses.',
  subTagline:  'Web Designer & Full Stack Developer creating modern, responsive, high-performance websites for businesses, schools, startups, and personal brands.',
  location:    'Haripur, KPK, Pakistan',
  email:       'iamsaifi17@gmail.com',
  phone:       '+92-318-5352563',
  whatsapp:    'https://wa.me/923450470036',
  whatsappMsg: 'https://wa.me/923450470036?text=Hi%20Muhammad%2C%20I%20would%20like%20to%20discuss%20a%20web%20design%20project.',

  social: {
    linkedin:  'https://www.linkedin.com/in/muhammad-saifullah-8a3469416',
    fiverr:    'https://www.fiverr.com/saifii1201',
    facebook:  'https://www.facebook.com/share/1ApyuC5MMY/',
    twitter:   'https://twitter.com/iamsaifi17',
    instagram: 'https://instagram.com/iamsaifi17',
    github:    'https://github.com/iamsaifi17',
  },

  seo: {
    title:       'Muhammad Saifullah | Web Designer & Full Stack Developer',
    description: 'Professional Web Designer & Full Stack Developer creating modern, responsive websites for businesses, schools, startups, and personal brands. Based in Pakistan.',
    keywords:    'web designer Pakistan, full stack developer Pakistan, website development, Next.js developer, Muhammad Saifullah',
    siteUrl:     'https://saifullah-portfolio-omega.vercel.app',
    ogImage:     '/images/og-image.jpg',
    twitterHandle: '@iamsaifi17',
  },

  about: {
    headline: 'Web Designer & Full Stack Developer Solving Real Problems',
    bio: [
      "I'm Muhammad Saifullah — a Web Designer & Full Stack Developer from Haripur, KPK, Pakistan. I design and develop complete web applications, from responsive user interfaces to scalable backend systems, helping businesses build a powerful online presence.",
      "With a BS English degree and strong self-taught development skills, I combine clean code with elegant design to deliver websites that perform, convert, and grow with your business. I specialize in Next.js, React, Tailwind CSS, and modern UI/UX design.",
      "I have built real live websites for businesses, schools, and personal brands worldwide. Whether you need a portfolio, a landing page, or a full business website, I bring professionalism, speed, and attention to detail to every project.",
    ],
    mission: "To help businesses, schools, and personal brands grow online through modern, fast, and beautiful websites — designed with intention, built with clean code, and delivered on time.",
    stats: [
      { value: '3+',   label: 'Live Websites Built'  },
      { value: 'BS',   label: 'English Graduate'      },
      { value: '7d',   label: 'Average Delivery'      },
      { value: '100%', label: 'Client Satisfaction'   },
    ],
  },

  skills: [
    { name: 'HTML5 & CSS3',           level: 92 },
    { name: 'JavaScript',             level: 80 },
    { name: 'React & Next.js',        level: 82 },
    { name: 'Tailwind CSS',           level: 90 },
    { name: 'Responsive Web Design',  level: 93 },
    { name: 'UI/UX Design',           level: 85 },
    { name: 'Git & GitHub',           level: 80 },
    { name: 'SEO & Performance',      level: 83 },
    { name: 'Vercel Deployment',      level: 95 },
    { name: 'Full Stack Development', level: 78 },
  ],

  services: [
    {
      id:          'business-website',
      icon:        '🏢',
      title:       'Business Websites',
      description: 'Professional websites for businesses of all sizes — built to impress customers, generate leads, and grow your brand online.',
      features:    ['Custom Design', 'Mobile Responsive', 'Contact Forms', 'WhatsApp Integration', 'SEO Ready', 'Fast Loading', 'Vercel Deployment'],
      price:       'Starting at $80',
      popular:     true,
    },
    {
      id:          'portfolio-website',
      icon:        '💼',
      title:       'Portfolio Websites',
      description: 'Stunning personal portfolio websites for freelancers, developers, and creatives who want to stand out and attract quality clients.',
      features:    ['Premium Design', 'Smooth Animations', 'Project Showcase', 'Testimonials', 'Contact Form', 'SEO Optimized', 'Mobile First'],
      price:       'Starting at $50',
      popular:     false,
    },
    {
      id:          'school-website',
      icon:        '🏫',
      title:       'School & Education Websites',
      description: 'Clean, professional websites for schools, colleges, and educational institutions — easy to navigate for everyone.',
      features:    ['Admissions Page', 'Staff Directory', 'Gallery Section', 'News & Events', 'Mobile Friendly', 'Easy to Update', 'Fast Loading'],
      price:       'Starting at $70',
      popular:     false,
    },
    {
      id:          'landing-page',
      icon:        '🚀',
      title:       'Landing Pages',
      description: 'High-converting landing pages designed to turn visitors into customers — perfect for product launches and campaigns.',
      features:    ['Conversion Focused', 'Fast Loading', 'CTA Optimized', 'Mobile First', 'Analytics Ready', 'Custom Design', 'SEO Ready'],
      price:       'Starting at $30',
      popular:     false,
    },
    {
      id:          'ui-design',
      icon:        '🎨',
      title:       'UI/UX Design',
      description: 'Modern interface design that looks beautiful and feels intuitive — creating digital experiences users love and return to.',
      features:    ['Custom UI Design', 'Modern Aesthetic', 'User Friendly', 'Brand Consistent', 'Responsive Layouts', 'Pixel Perfect', 'Fast Delivery'],
      price:       'Starting at $25',
      popular:     false,
    },
  ],

  portfolio: [
    {
      id:       1,
      title:    'MashAllah Parrot House',
      client:   'Parrot Business — Karachi, Pakistan',
      category: 'Web Development',
      tags:     ['Next.js', 'Business Website', 'WhatsApp Integration'],
      excerpt:  'A modern premium website for a parrot business featuring bird listings, responsive design, WhatsApp integration, and elegant UI.',
      metrics:  { Tech: 'Next.js', Type: 'Business', Status: 'Live' },
      image:    '/images/portfolio/portfolio-1.jpg',
      liveUrl:  'https://mashallah-parrot-house-giml.vercel.app/',
    },
    {
      id:       2,
      title:    'Bright School',
      client:   'Educational Institution',
      category: 'Web Development',
      tags:     ['Next.js', 'School Website', 'Responsive'],
      excerpt:  'A clean and responsive educational website with professional layouts, admissions info, and user-friendly navigation.',
      metrics:  { Tech: 'Next.js', Type: 'Education', Status: 'Live' },
      image:    '/images/portfolio/portfolio-2.jpg',
      liveUrl:  'https://bright-school-ten.vercel.app/',
    },
    {
      id:       3,
      title:    'Joylyn Rosa Portfolio',
      client:   'SEO Content Writer — Philippines',
      category: 'Web Development',
      tags:     ['Next.js', 'Portfolio', 'Animations'],
      excerpt:  'A modern personal portfolio website with premium design, smooth animations, and professional presentation.',
      metrics:  { Tech: 'Next.js', Type: 'Portfolio', Status: 'Live' },
      image:    '/images/portfolio/portfolio-3.jpg',
      liveUrl:  'https://jolynrosa123-gtnc.vercel.app/',
    },
    {
      id:       4,
      title:    'Muhammad Saifullah Portfolio',
      client:   'Personal Brand',
      category: 'Web Development',
      tags:     ['Next.js', 'Portfolio', 'Full Stack'],
      excerpt:  'This very website — a fully responsive professional portfolio built with Next.js, Tailwind CSS, and Framer Motion.',
      metrics:  { Tech: 'Next.js', Type: 'Portfolio', Status: 'Live' },
      image:    '/images/portfolio/portfolio-4.jpg',
      liveUrl:  'https://saifullah-portfolio-omega.vercel.app',
    },
  ],

  testimonials: [
    {
      id:          1,
      name:        'Joylyn Rosa',
      role:        'SEO Content Writer',
      country:     'Philippines',
      rating:      5,
      text:        "I'm so glad I found Muhammad Saifullah. I needed a portfolio that would help me stand out and attract clients, and he absolutely delivered. It looked even better than I imagined. He really listened, paid attention to the little details, and made sure everything felt right. Couldn't be happier!",
      linkedinUrl: 'https://www.linkedin.com/posts/joylyn-rosa-040143415_joylyn-rosa-seo-content-writer-virtual-activity-7481960809573699584-dM36',
      websiteUrl:  'https://jolynrosa123-gtnc.vercel.app/',
      image:       '/images/testimonials/joylyn-rosa.jpg',
    },
    {
      id:          2,
      name:        'Ahmed Khan',
      role:        'Founder, Vision Digital',
      country:     'Pakistan',
      rating:      5,
      text:        'Muhammad delivered a modern website that exceeded our expectations. His communication, attention to detail, and commitment to quality made the entire experience smooth and professional. Highly recommend.',
      linkedinUrl: null,
      websiteUrl:  null,
      image:       '/images/testimonials/client-2.jpg',
    },
  ],

  resume: {
    downloadUrl: '/resume/Muhammad-Saifullah-CV.pdf',
    summary: 'Web Designer & Full Stack Developer with a BS English degree and strong self-taught technical skills. Experienced in building modern responsive websites using Next.js, React, and Tailwind CSS. Proficient in AI tools including ChatGPT, Claude, and Gemini. Owns multiple live websites demonstrating real design and development capability.',
    experience: [
      {
        title:   'Freelance Web Designer & Full Stack Developer',
        company: 'Self-Employed',
        period:  '2024 – Present',
        points:  [
          'Designed and developed 3+ live websites for real clients using Next.js and Tailwind CSS',
          'Built responsive mobile-first UI/UX interfaces with modern animations and clean code',
          'Integrated WhatsApp, contact forms, booking systems, and admin dashboards',
          'Delivered complete web solutions from design to deployment on Vercel',
          'Used AI tools to accelerate development and optimize workflows',
        ],
      },
      {
        title:   'Research Writer & Content Analyst',
        company: 'Academic Research Project',
        period:  'Jan 2026 – Jun 2026',
        points:  [
          'Researched and wrote a long-form academic paper on postcolonial literature',
          'Demonstrated ability to research complex topics and convert them into clear narratives',
          'Used AI tools to synthesize research and optimize content quality',
        ],
      },
    ],
    education: [
      { degree: 'Bachelor of Science in English (BS English)', school: 'Govt. Akhtar Nawaz Khan (Shaheed) Degree College KTS', period: '2022 – 2026' },
      { degree: 'Diploma in Surgical Technician', school: 'FIMS', period: '2020' },
      { degree: 'FSC Premedical', school: 'Govt. PG College Haripur', period: '2020' },
    ],
    techSkills:    ['HTML5', 'CSS3', 'JavaScript', 'React', 'Next.js', 'Tailwind CSS', 'Responsive Design', 'UI/UX Design', 'Git & GitHub', 'SEO Optimization', 'Full Stack Development', 'Vercel Deployment'],
    contentSkills: ['Technical Writing', 'SEO Content', 'Brand Storytelling', 'AI-Assisted Writing', 'Documentation'],
    aiTools:       ['ChatGPT', 'Claude (Anthropic)', 'Gemini'],
    languages:     ['English (Fluent)', 'Urdu (Native)', 'Pashto', 'Hindko', 'Punjabi'],
  },

  blogPosts: [
    {
      slug:       'ux-research-half-true',
      title:      "Most of What You've Been Told About UX Research Is Half True",
      excerpt:    'The five-users rule, heuristic evaluation, A/B testing, and AI-simulated participants — the UX industry repeats these heuristics constantly. What does the actual research say?',
      category:   'Research',
      readTime:   '10 min read',
      date:       '2026-07-01',
      image:      '/images/blog/blog-research.jpg',
      featured:   true,
      isResearch: true,
      abstract:   'A critical examination of four widely-cited methodologies in UX and web design practice.',
      keywords:   ['UX Research', 'Usability Evaluation', 'Accessibility', 'Evidence-Based Design'],
    },
    {
      slug:     'website-copy-that-converts',
      title:    'How to Write Website Copy That Actually Converts',
      excerpt:  'Design gets people to stay for three seconds. Copy makes them stay for three minutes. Here is how to write website words that turn visitors into clients.',
      category: 'Business',
      readTime: '6 min read',
      date:     '2025-06-10',
      image:    '/images/blog/blog-1.jpg',
      featured: false,
    },
    {
      slug:     'signs-website-costing-clients',
      title:    '5 Signs Your Business Website Is Costing You Clients',
      excerpt:  'A website should be your best salesperson — but a poorly built one quietly chases clients away. Here are the five warning signs.',
      category: 'Web Development',
      readTime: '5 min read',
      date:     '2025-05-22',
      image:    '/images/blog/blog-2.jpg',
      featured: false,
    },
    {
      slug:     'linkedin-content-strategy-freelancers',
      title:    'A Simple LinkedIn Strategy for Freelancers Who Hate Self-Promotion',
      excerpt:  'You do not need to be loud or salesy to get results from LinkedIn. Here is a small, consistent system that actually brings in clients.',
      category: 'Business',
      readTime: '7 min read',
      date:     '2025-05-05',
      image:    '/images/blog/blog-3.jpg',
      featured: false,
    },
  ],

  faq: [
    {
      q: 'What types of websites do you build?',
      a: 'I build business websites, portfolio websites, school and education websites, landing pages, and complete web applications. All websites are built with Next.js and Tailwind CSS — fully responsive, fast, and SEO-ready.',
    },
    {
      q: 'How long does it take to build a website?',
      a: 'A landing page can be done in 24–48 hours. A standard website takes 3–7 days. A complex web application may take 7–14 days. I always give a clear timeline upfront.',
    },
    {
      q: 'How much does a website cost?',
      a: 'A landing page starts at $30, a portfolio website starts at $50, a school website starts at $70, and a business website starts at $80. Transparent pricing — no hidden charges.',
    },
    {
      q: 'Will my website work on mobile phones?',
      a: 'Absolutely. Every website I build is fully mobile-responsive and tested across phones, tablets, and desktops.',
    },
    {
      q: 'Do you host the website for free?',
      a: 'Yes! I deploy all websites on Vercel for free. You only need a domain name if you want one — around $10–$15 per year.',
    },
    {
      q: 'Can I update the website myself after it is built?',
      a: 'Yes — I build websites so content is easy to edit. I also provide a simple guide for making changes without coding knowledge.',
    },
    {
      q: 'Do you offer revisions?',
      a: 'Yes — every project includes 2 rounds of free revisions. We keep working until everything is exactly right.',
    },
    {
      q: 'How do I get started?',
      a: 'Simply message me on WhatsApp and tell me about your project. I will reply quickly with a proposal, timeline, and price.',
    },
  ],
};
