export const SITE_CONFIG = {
  name:        'Muhammad Saifullah',
  shortName:   'Muhammad Saifullah',
  tagline:     'Words That Persuade. Websites That Impress.',
  subTagline:  'Freelance Copywriter & Web Developer helping brands communicate clearly and look stunning online.',
  location:    'Pakistan',
  email:       'iamsaifi17@gmail.com',
  phone:       '+92-308-2612190',

  social: {
    linkedin:  'https://www.linkedin.com/in/muhammad-saifullah-8a3469416',
    fiverr:    'https://www.fiverr.com/saifii1201',
    twitter:   'https://twitter.com/iamsaifi17',
    instagram: 'https://instagram.com/iamsaifi17',
    github:    'https://github.com/iamsaifi17',
  },

  seo: {
    title:       'Muhammad Saifullah | Freelance Copywriter & Web Developer',
    description: 'BS English graduate from Pakistan. Professional copywriter and web developer specializing in LinkedIn content, website development, AI-assisted writing, and social media. Serving international clients.',
    keywords:    'copywriter Pakistan, web developer Pakistan, LinkedIn content writer, freelance writer, Muhammad Saifullah, website developer Pakistan',
    siteUrl:     'https://saifullah-portfolio.vercel.app',
    ogImage:     '/images/og-image.jpg',
    twitterHandle: '@iamsaifi17',
  },

  about: {
    headline: 'Copywriter. Web Developer. Creative Problem Solver.',
    bio: [
      "I'm Muhammad Saifullah — a BS English graduate from Pakistan with a passion for two things: powerful words and beautiful websites. I combine the art of persuasive writing with modern web development to help businesses grow their online presence from every angle.",
      "As a copywriter, I craft content that connects with audiences and drives results — from LinkedIn posts to product descriptions to email sequences. As a web developer, I build fast, responsive, professional websites using Next.js and modern technologies.",
      "I am an ambitious self-learner based in Pakistan, working with international clients who want both great writing AND a great website — without hiring two different people. If you need words that sell and a website that impresses, I am your guy.",
    ],
    mission: "To help businesses and personal brands grow online through the perfect combination of compelling content and professional web development — delivering real results at honest prices.",
    stats: [
      { value: 'BS',   label: 'English Graduate'    },
      { value: '2+',   label: 'Websites Built'       },
      { value: '48h',  label: 'Average Turnaround'   },
      { value: '100%', label: 'Commitment'            },
    ],
  },

  skills: [
    { name: 'English Writing & Grammar',   level: 95 },
    { name: 'Persuasive Copywriting',      level: 88 },
    { name: 'Web Development (Next.js)',   level: 80 },
    { name: 'LinkedIn Content Writing',    level: 85 },
    { name: 'AI-Assisted Writing (GPT)',   level: 90 },
    { name: 'Social Media Content',        level: 87 },
    { name: 'Responsive Web Design',       level: 78 },
    { name: 'SEO Writing & Optimization',  level: 82 },
  ],

  services: [
    {
      id:          'web-development',
      icon:        '💻',
      title:       'Website Development',
      description: 'Professional, fast, and fully responsive websites built with Next.js and Tailwind CSS. Portfolio sites, business websites, landing pages — delivered ready to publish.',
      features:    ['Portfolio Websites', 'Business Websites', 'Landing Pages', 'Next.js & React', 'Mobile Responsive', 'SEO Ready', 'Vercel Deployment'],
      price:       'Starting at $50',
      popular:     true,
    },
    {
      id:          'copywriting',
      icon:        '✍️',
      title:       'Persuasive Copywriting',
      description: 'Sales pages, landing pages, product descriptions, and marketing copy that compels readers to take action. Every word earns its place.',
      features:    ['Sales Page Copy', 'Landing Page Copy', 'Product Descriptions', 'Ad Copy', 'Email Sequences'],
      price:       'Starting at $10',
      popular:     false,
    },
    {
      id:          'linkedin',
      icon:        '💼',
      title:       'LinkedIn Content Writing',
      description: 'Build authority on LinkedIn with posts, articles, and profile optimization that grow your network and attract opportunities.',
      features:    ['LinkedIn Posts', 'Profile Optimization', 'Article Writing', 'Thought Leadership', 'Engagement Strategy'],
      price:       'Starting at $15/post',
      popular:     false,
    },
    {
      id:          'ai-content',
      icon:        '🤖',
      title:       'AI-Assisted Content',
      description: 'Harness the speed of AI with the quality of human editing. High-volume content without sacrificing voice or accuracy.',
      features:    ['Blog Posts & Articles', 'Bulk Content Packages', 'Content Repurposing', 'AI Prompt Engineering', 'Human Review & Polish'],
      price:       'Starting at $8/piece',
      popular:     false,
    },
    {
      id:          'social-media',
      icon:        '📱',
      title:       'Social Media Content',
      description: 'Scroll-stopping captions and posts for Instagram, Twitter/X, Facebook, and TikTok that build community and drive engagement.',
      features:    ['Caption Writing', 'Content Calendars', 'Hashtag Strategy', 'Story Copy', 'Reel Scripts'],
      price:       'Starting at $5/post',
      popular:     false,
    },
  ],

  portfolio: [
    {
      id:       1,
      title:    'MashAllah Parrot House',
      client:   'Parrot Shop — Karachi, Pakistan',
      category: 'Web Development',
      tags:     ['Next.js', 'Business Website', 'SEO'],
      excerpt:  'A full professional website for a parrot shop in Karachi — complete with product listings, booking system, admin dashboard, and local SEO optimization.',
      metrics:  { Tech: 'Next.js', Pages: '8+', Status: 'Live' },
      image:    '/images/portfolio/portfolio-1.jpg',
      liveUrl:  'https://mashallah-parrot-house-giml.vercel.app/',
    },
    {
      id:       2,
      title:    'Personal Portfolio Website',
      client:   'Muhammad Saifullah',
      category: 'Web Development',
      tags:     ['Next.js', 'Portfolio', 'Tailwind CSS'],
      excerpt:  'This very website — a fully responsive professional portfolio built with Next.js, Tailwind CSS, and Framer Motion animations. Deployed free on Vercel.',
      metrics:  { Tech: 'Next.js', Pages: '7+', Status: 'Live' },
      image:    '/images/portfolio/portfolio-2.jpg',
      liveUrl:  'https://saifullah-portfolio.vercel.app',
    },
    {
      id:       3,
      title:    'LinkedIn Profile Optimization',
      client:   'Personal Brand Sample',
      category: 'Copywriting',
      tags:     ['LinkedIn', 'Profile', 'Personal Brand'],
      excerpt:  'A complete LinkedIn profile rewrite — optimized headline, about section, and experience descriptions to attract recruiters and international clients.',
      metrics:  { Type: 'Sample', Quality: 'High', Focus: 'LinkedIn' },
      image:    '/images/portfolio/portfolio-3.jpg',
      liveUrl:  null,
    },
    {
      id:       4,
      title:    'Product Description Pack',
      client:   'E-Commerce Sample',
      category: 'Copywriting',
      tags:     ['E-Commerce', 'Product Copy', 'SEO'],
      excerpt:  'A set of 5 SEO-optimized product descriptions for electronics — written to inform, persuade, and convert browsers into buyers.',
      metrics:  { Type: 'Sample', Items: '5', Style: 'SEO' },
      image:    '/images/portfolio/portfolio-4.jpg',
      liveUrl:  null,
    },
    {
      id:       5,
      title:    'Social Media Content Calendar',
      client:   'Fashion Brand Sample',
      category: 'Social Media',
      tags:     ['Instagram', 'Facebook', 'Captions'],
      excerpt:  'A 7-day social media content calendar with captions, hashtags, and post ideas for a fashion brand — ready to publish immediately.',
      metrics:  { Type: 'Sample', Posts: '7', Platforms: '2' },
      image:    '/images/portfolio/portfolio-5.jpg',
      liveUrl:  null,
    },
    {
      id:       6,
      title:    'AI-Assisted Blog Article',
      client:   'Tech Blog Sample',
      category: 'AI Content',
      tags:     ['Blog', 'SEO', 'AI-Assisted'],
      excerpt:  'A 1,000-word SEO blog article — researched, AI-assisted, and fully human-edited for accuracy, readability, and search ranking.',
      metrics:  { Type: 'Sample', Words: '1000+', Style: 'SEO Blog' },
      image:    '/images/portfolio/portfolio-6.jpg',
      liveUrl:  null,
    },
  ],

  testimonials: [
    {
      id:      1,
      name:    'Your Client Name Here',
      role:    'Client Job Title',
      country: '🇺🇸 United States',
      rating:  5,
      text:    'This is where your first real client review will go. As you complete projects, ask clients for a short review and add it here. Great reviews build trust and bring more clients.',
      image:   '/images/testimonials/client-1.jpg',
    },
    {
      id:      2,
      name:    'Your Client Name Here',
      role:    'Client Job Title',
      country: '🇬🇧 United Kingdom',
      rating:  5,
      text:    'This is where your second client review will go. Even one or two genuine reviews make a huge difference. Start with free or discounted work to get your first testimonials.',
      image:   '/images/testimonials/client-2.jpg',
    },
    {
      id:      3,
      name:    'Your Client Name Here',
      role:    'Client Job Title',
      country: '🇨🇦 Canada',
      rating:  5,
      text:    'Add your third client review here. Ask every client after delivery — most happy clients are glad to leave a few words. Their words sell better than yours.',
      image:   '/images/testimonials/client-3.jpg',
    },
    {
      id:      4,
      name:    'Your Client Name Here',
      role:    'Client Job Title',
      country: '🇦🇺 Australia',
      rating:  5,
      text:    'Your fourth client review goes here. Build your reputation one project at a time — every great developer and writer started exactly where you are right now.',
      image:   '/images/testimonials/client-4.jpg',
    },
  ],

  blogPosts: [
    {
      slug:     'linkedin-content-strategy-2025',
      title:    'The LinkedIn Content Strategy That Gets You Noticed in 30 Days',
      excerpt:  'Most LinkedIn posts disappear into the void. Here is the exact framework I use to write posts that start conversations, build authority, and attract clients.',
      category: 'LinkedIn',
      readTime: '6 min read',
      date:     '2025-01-15',
      image:    '/images/blog/blog-1.jpg',
      featured: true,
    },
    {
      slug:     'ai-copywriting-human-touch',
      title:    'How I Use AI to Write Faster Without Losing the Human Touch',
      excerpt:  'AI will not replace writers — but writers who use AI will replace those who do not. Here is my exact workflow for producing high-quality content at scale.',
      category: 'AI Content',
      readTime: '5 min read',
      date:     '2025-01-08',
      image:    '/images/blog/blog-2.jpg',
      featured: false,
    },
    {
      slug:     'product-descriptions-that-sell',
      title:    '5 Product Description Formulas That Actually Drive Sales',
      excerpt:  'Your product description is your silent salesperson. These 5 formulas will transform how browsers become buyers — with real before and after examples.',
      category: 'Copywriting',
      readTime: '7 min read',
      date:     '2024-12-20',
      image:    '/images/blog/blog-3.jpg',
      featured: false,
    },
  ],

  faq: [
    {
      q: 'Do you build websites as well as write content?',
      a: 'Yes! I offer both services. I build professional websites using Next.js and Tailwind CSS, and I also write all the content for them. You can hire me for just the website, just the writing, or both together for a complete package.',
    },
    {
      q: 'Are you a fresh graduate or do you have experience?',
      a: 'I am a fresh BS English graduate who has already built multiple real live websites and developed strong copywriting skills. I am passionate, hardworking, and offer competitive rates. Every expert started somewhere — I am committed to delivering my best on every project.',
    },
    {
      q: 'What types of websites do you build?',
      a: 'I build portfolio websites, business websites, and landing pages using Next.js and Tailwind CSS. All websites are fully responsive, SEO-friendly, and deployed free on Vercel. I can add contact forms, booking systems, admin dashboards, and more.',
    },
    {
      q: 'What is your typical turnaround time?',
      a: 'For writing projects — 48 hours. For websites — 3 to 7 days depending on complexity. I always give a clear timeline before starting and keep you updated throughout.',
    },
    {
      q: 'Do you offer revisions?',
      a: 'Yes — all projects include 2 rounds of free revisions. I want you to be completely satisfied. If something does not feel right, we will fix it.',
    },
    {
      q: 'How do payments work?',
      a: 'For new clients I require 50% upfront and 50% on delivery. Payment via PayPal, Wise, or Fiverr. I always send a clear invoice for your records.',
    },
    {
      q: 'Can you do both the website AND the content?',
      a: 'Absolutely — and this is where I offer the most value. Hiring one person for both your website and your content saves you money, time, and the hassle of coordinating between two freelancers. Ask me about combination packages.',
    },
    {
      q: 'How do I get started?',
      a: 'Click the Hire Me button, fill out the contact form with your project details, and I will respond within 24 hours with a proposal, timeline, and price.',
    },
  ],
};
